"use client";

import { ChevronDown, Minus, Plus } from "lucide-react";
import { useState } from "react";

export function DarkHomeFaq() {
  const [openIndex, setOpenIndex] = useState(-1);
  return (
    <section className="w-full space-y-6">
      <p className="text-sm font-bold text-[#dbe2fd] text-center uppercase tracking-[0.2em]">
        FAQ
      </p>
      <div className="space-y-3">
        {faqItems.map((item, index) => {
          const isOpen = openIndex === index;
          return (
            <div key={item.question} className="glass-panel overflow-hidden">
              <button
                type="button"
                className={`flex w-full items-center justify-between p-5 cursor-pointer text-left transition-colors ${isOpen ? "" : "hover:bg-white/5"}`}
                aria-expanded={isOpen}
                onClick={() => setOpenIndex(isOpen ? -1 : index)}
              >
                <span className="text-white font-bold text-sm">{item.question}</span>
                <ChevronDown
                  size={18}
                  strokeWidth={2}
                  className="text-[#90909a] shrink-0 transition-transform duration-200"
                  style={{ transform: isOpen ? "rotate(180deg)" : "rotate(0deg)" }}
                />
              </button>
              {isOpen && (
                <div className="px-5 pb-5 pt-0">
                  <p className="text-[#c6c5d0] text-sm leading-relaxed">{item.answer}</p>
                </div>
              )}
            </div>
          );
        })}
      </div>
    </section>
  );
}

const faqItems = [
  {
    question: "What exactly does Metric look at?",
    answer:
      "For every stock, we pull together the current price and day move, where it sits in its 52-week range, trading volume, fundamentals like P/E and margins, what its closest peers are doing, recent news, and technical signals. The AI then reads all of that together and explains what it means in plain language.",
  },
  {
    question: "Will Metric tell me whether to buy or sell?",
    answer:
      "It will not, and that is intentional. Metric is here to help you understand a stock, not to make the decision for you. You will never see a buy rating, target price, or stop loss anywhere on the platform. What you will get is a clear read of the data so you can decide for yourself.",
  },
  {
    question: "Where does the data come from?",
    answer:
      "Live prices and fundamentals come from Upstox and Yahoo Finance. News and technical signals are sourced through Tradient. The analysis is generated by Claude, Anthropic's AI model. We pull from multiple sources so you get a fuller picture than any single feed can provide.",
  },
  {
    question: "How up to date is the information?",
    answer:
      "Market prices refresh with each analysis. Fundamentals update when your data providers push new filings, which usually happens quarterly. Each report shows you the timestamp of the data it was built on so you always know how fresh the numbers are.",
  },
  {
    question: "Can I search by company name instead of the ticker?",
    answer:
      "Absolutely. Just type the company name and Metric will find the closest NSE or BSE listed match for you. You can also type the ticker directly if you already know it. Either way works.",
  },
];

export function HomeFaq() {
  const [openIndex, setOpenIndex] = useState(-1);

  return (
    <section className="animate-entrance delay-4 surface p-4">
      <div className="mb-3 flex items-center justify-between gap-3">
        <h2
          className="text-[25px] leading-none text-black [text-shadow:0.45px_0_0_#000,-0.45px_0_0_#000]"
          style={{ fontFamily: 'Georgia, "Times New Roman", Times, serif', fontWeight: 700 }}
        >
          Questions, answered
        </h2>
        <span className="border-2 border-black bg-metric-finance-accent-soft px-2 py-1 font-mono text-[9px] font-black uppercase tracking-[0.08em] text-metric-blue">
          FAQ
        </span>
      </div>

      <div className="grid gap-2">
        {faqItems.map((item, index) => {
          const isOpen = openIndex === index;
          return (
            <div key={item.question} className="overflow-hidden border-2 border-black bg-white">
              <button
                type="button"
                className="faq-trigger flex w-full items-center justify-between gap-4 px-3 py-3 text-left"
                aria-expanded={isOpen}
                onClick={() => setOpenIndex(isOpen ? -1 : index)}
              >
                <span className="font-mono text-sm font-black leading-5 tracking-[0.02em] text-black">
                  {item.question}
                </span>
                <span className="neo-press flex h-7 w-7 shrink-0 items-center justify-center border-2 border-black bg-metric-finance-accent-soft">
                  {isOpen ? <Minus size={16} strokeWidth={2.8} /> : <Plus size={16} strokeWidth={2.8} />}
                </span>
              </button>
              <div className={`faq-answer ${isOpen ? "faq-answer-open" : ""}`}>
                <p className="border-t-2 border-black px-3 pb-4 pt-3 text-sm font-medium leading-6 text-metric-muted">
                  {item.answer}
                </p>
              </div>
            </div>
          );
        })}
      </div>
    </section>
  );
}
